language: perl
perl:
   - "5.16"
   - "5.14"
   - "5.12"

before_install:
   # also initialize sass2scss submodule
   - git submodule update --init --recursive
install:
   # Deal with all of the DZIL dependancies, quickly and quietly
   - cpanm --quiet --notest --skip-satisfied CSS::Sass
before_script:
   # also initialize sass2scss submodule
   # - git submodule update --init --recursive
script:
   - perl Build.PL
   - ./Build verbose=1
   - ./Build test verbose=1
   - ./Build install verbose=1
